Fix/gather monitoring base metrics collector (#16)
* fix/monitoring-review: disable GF discovery, review comments

* fix/monitoring-regex: discovery variables metrics

* chore: avoid err "ERROR: on line 44..."

* fix/monitoring-jq: follow redirects when download

* fix/monit-type: DATE_START has wrong var

* chore/monit-discovery: check dashboards file

* chore/monit-discovery: avoid err checking dashboards file check

* chore/monit-discovery: typo

* monitoring: removing grafana and jq deps

* fix/monitoring: typos

* fix/monitoring: reordering fns / clean code

* fix/monitoring: use one prom_get_query metric

* fix/monitoring: changing the scope of global vars

* fix/monitoring: review qstr and err handling

* fix/monitoring: review qstr and err handling

* fix/monitoring: adjust cm

* chore/monitoring: improve info for query fn

* chore/monitoring: improve info for query fn

* fix/monitoring: fixes on api call fn

* chore/monitoring: improve info for query fn

diff --git a/collection-scripts/gather_monitoring b/collection-scripts/gather_monitoring
--- a/collection-scripts/gather_monitoring
+++ b/collection-scripts/gather_monitoring
@@ -10,20 +10,17 @@
 # - GAHTER_MONIT_END_DATE: ending human readable date string (date -d). Default: "now".
 # - GAHTER_MONIT_QUERY_STEP: metric resolution to get from Prometheus. Default: "1m".
 # - GATHER_MONIT_CUSTOM_METRICS: list of additional metrics name to be collected. Default: Undefined
-# - GATHER_MONIT_DISCOVERY_GRAFANA: manage Grafana metrics discovery, 'no' is disabled. Default: != 'no'
 # - GATHER_MONIT_DISCOVERY_PREFIXES: discovery metrics by prefixes. Default: ''
 # - GAHTER_MONIT_TOKEN: optional service account token to gather Prometheus and Grafana API. Default: Undefined
 #
 # To create the ConfigMap:
 # $ echo -e 'GAHTER_MONIT_START_DATE="15 days ago"\nGAHTER_MONIT_QUERY_STEP="5m"' > env
 # $ echo -e 'GATHER_MONIT_CUSTOM_METRICS="up"' > env
-# $ echo -e 'GATHER_MONIT_DISCOVERY_GRAFANA="no"\nGATHER_MONIT_CUSTOM_METRICS="up"' > env
 # $ echo -e 'GATHER_MONIT_DISCOVERY_PREFIXES="apiserver_"' > env
 # $ oc create configmap must-gather-env -n openshift-monitoring --from-file=env=env
 #
 # References:
 # - Prometheus API: https://prometheus.io/docs/prometheus/latest/querying/api/
-# - Grafana API: https://grafana.com/docs/grafana/latest/http_api/dashboard/
 
 #Safeguards
 set -o pipefail
@@ -33,227 +30,179 @@ err_report() {
 }
 trap 'err_report $LINENO' ERR
 
-GAHTER_MONIT_START_DATE_DEFAULT="7 days ago"
-GAHTER_MONIT_END_DATE_DEFAULT="now"
-GAHTER_MONIT_QUERY_STEP_DEFAULT="1m"
-GATHER_MONIT_DISCOVERY_GRAFANA_DEFAULT="yes"
+declare -r GAHTER_MONIT_START_DATE_DEFAULT="7 days ago"
+declare -r GAHTER_MONIT_END_DATE_DEFAULT="now"
+declare -r GAHTER_MONIT_QUERY_STEP_DEFAULT="1m"
 
-MONIT_NS="openshift-monitoring"
-MONIT_ENV="must-gather-env"
+declare -r MONIT_NS="openshift-monitoring"
+declare -r MONIT_ENV="must-gather-env"
 
-JQ_PATH=$(command -v jq 2>/dev/null)
-CURL_CMD=(curl --fail -sk)
+declare -r CURL_CMD=(curl --fail -sk)
 
-BASE_COLLECTION_PATH="/must-gather"
-MONITORING_PATH="${BASE_COLLECTION_PATH}/monitoring"
-PROM_PATH="${MONITORING_PATH}/prometheus"
-GF_PATH="${MONITORING_PATH}/grafana"
+declare -r BASE_COLLECTION_PATH="/must-gather"
+declare -r MONITORING_PATH="${BASE_COLLECTION_PATH}/monitoring"
+declare -r PROM_PATH="${MONITORING_PATH}/prometheus"
+declare -r CA_BUNDLE="${MONITORING_PATH}/ca-bundle.crt"
 
-test -d "${PROM_PATH}" || mkdir -p "${PROM_PATH}"
-test -d "${GF_PATH}" || mkdir -p "${GF_PATH}"
+# Setting: Session token, overwriten by GAHTER_MONIT_TOKEN
+declare -r SS_TOKEN="${GAHTER_MONIT_TOKEN:-$(oc whoami -t)}"
+declare -r SA_TOKEN="$(oc sa get-token default)"
+declare -r PROM_HOST=$(oc -n "${MONIT_NS}" get route prometheus-k8s -o jsonpath='{.spec.host}{"\n"}')
+declare -r PROM_API="/api/v1"
 
-echo "INFO: Get custom metrics from ConfigMap ${MONIT_ENV} on project ${MONIT_NS}"
-oc -n "${MONIT_NS}" \
-    get cm "${MONIT_ENV}" \
-    -o jsonpath='{.data.env}' > "${MONITORING_PATH}/env" 2> /dev/null
-if [[ $? -eq 0 ]]; then
-    echo "INFO: Loading custom environments variables from ${MONITORING_PATH}/env"
-    source "${MONITORING_PATH}/env"
-else
-    echo "INFO: Unable to load custom environments from ConfigMap, ignoring."
-fi
+function get_env {
+    oc -n "${MONIT_NS}" extract "cm/${MONIT_ENV}" \
+        --keys=env \
+        --to="${MONITORING_PATH}/" 2>&1 >/dev/null || true
 
-#Session token, overwriten by GAHTER_MONIT_TOKEN
-OCP_TOKEN="${GAHTER_MONIT_TOKEN:-$(oc whoami -t)}"
-SA_TOKEN="$(oc sa get-token default)"
-
-# this is a CA bundle we need to verify the routes
-oc -n openshift-config-managed \
-    get cm default-ingress-cert \
-    -o jsonpath='{.data.ca-bundle\.crt}' > "${MONITORING_PATH}/ca-bundle.crt"
-
-# Timestamp to Prometheus query time range
-_START_HUNAN=${GAHTER_MONIT_START_DATE:-${GAHTER_MONIT_START_DATE_DEFAULT}}
-DATE_START=$(date -d "${_START}" +%s)
-_END_HUMAN=${GAHTER_MONIT_END_DATE:-${GAHTER_MONIT_END_DATE_DEFAULT}}
-DATE_END=$(date -d "${_END_HUMAN}" +%s)
-
-# Metric resolution: If the resolution is too low, the API will deny due to 11k limitation
-QUERY_STEP=${GAHTER_MONIT_QUERY_STEP:-${GAHTER_MONIT_QUERY_STEP_DEFAULT}}
-
-PROM_HOST=$(oc -n "${MONIT_NS}" get route prometheus-k8s -o jsonpath='{.spec.host}{"\n"}')
-PROM_URL="https://${PROM_HOST}"
-
-GF_HOST=$(oc -n "${MONIT_NS}" get route grafana -o jsonpath='{.spec.host}{"\n"}')
-GF_URL="https://${GF_HOST}"
-
-echo "INFO: Metrics config time range from=${DATE_START} to=${DATE_END} step=${QUERY_STEP}"
-echo "INFO: Config Env GAHTER_MONIT_START_DATE: ${GAHTER_MONIT_START_DATE}"
-echo "INFO: Config Env GAHTER_MONIT_END_DATE: ${GAHTER_MONIT_END_DATE}"
-echo "INFO: Config Env GAHTER_MONIT_QUERY_STEP: ${GAHTER_MONIT_QUERY_STEP}"
-echo "INFO: Config Env GATHER_MONIT_CUSTOM_METRICS: ${GATHER_MONIT_CUSTOM_METRICS}"
-echo "INFO: Config Env GATHER_MONIT_DISCOVERY_PREFIXES: ${GATHER_MONIT_DISCOVERY_PREFIXES}"
-echo "INFO: Config Env GATHER_MONIT_DISCOVERY_GRAFANA: ${GATHER_MONIT_DISCOVERY_GRAFANA}"
-echo "INFO: Prometheus endpoint URL: ${PROM_URL}"
-echo "INFO: Grafana endpoint URL: ${GF_URL}"
-
-function install_jq() {
-
-    if [[ -f ${JQ_PATH} ]]; then
-        return
+    echo "INFO: Get custom metrics from ConfigMap ${MONIT_ENV} on project ${MONIT_NS}"
+    if [[ -s "${MONITORING_PATH}/env" ]]; then
+        echo "INFO: Loading custom environments variables from ${MONITORING_PATH}/env"
+        source "${MONITORING_PATH}/env"
+    else
+        echo "INFO: Unable to load custom environments from ConfigMap, ignoring."
     fi
-
-    # install jq from binary (required to Dashnoard parser)
-    export JQ_PATH=/usr/local/bin/jq
-    "${CURL_CMD[@]}" -o "${JQ_PATH}" \
-      https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && \
-      chmod +x "${JQ_PATH}"
 }
 
-# Make a query (single metric) to Prometheus API /api/v1/query_range
-function prom_query_range() {
-    QUERY=$1
-    METRIC_FILE=${2:-$(echo "${QUERY}" |awk -F'\(' '{print$1}')}
-
-    # The metrics are ziped to decrease the datatransfer
-    "${CURL_CMD[@]}" \
-        -H "Authorization: Bearer ${OCP_TOKEN}" \
-        -H "Accept-encoding: gzip" \
-        --data-urlencode "query=${QUERY}" \
-        --data-urlencode "start=${DATE_START}" \
-        --data-urlencode "end=${DATE_END}" \
-        --data-urlencode "step=${QUERY_STEP}" \
-        "${PROM_URL}/api/v1/query_range" > "${PROM_PATH}/metric-${METRIC_FILE}.json.gz"
+# this is a CA bundle we need to verify the monitoring route,
+# we will write it to disk so we can use it in the flag
+function get_ca_bundle {
+    oc -n openshift-config-managed \
+        get cm default-ingress-cert \
+        -o jsonpath='{.data.ca-bundle\.crt}' > "${CA_BUNDLE}"
 }
 
-# Gather metrics defined on environment GATHER_MONIT_CUSTOM_METRICS
-function get_custom_metrics() {
+function init {
+
+    test -d "${PROM_PATH}" || mkdir -p "${PROM_PATH}"
+
+    get_ca_bundle
+
+    get_env
+
+    # Setting: Timestamp to Prometheus' query range
+    declare -r _START_HUNAN=${GAHTER_MONIT_START_DATE:-${GAHTER_MONIT_START_DATE_DEFAULT}}
+    declare -g DATE_START=$(date -d "${_START_HUNAN}" +%s)
+    declare -r _END_HUMAN=${GAHTER_MONIT_END_DATE:-${GAHTER_MONIT_END_DATE_DEFAULT}}
+    declare -g DATE_END=$(date -d "${_END_HUMAN}" +%s)
+
+    # Setting: Metric resolution. Low resolution in longer range could be limited to 11k datapoints
+    declare -g QUERY_STEP=${GAHTER_MONIT_QUERY_STEP:-${GAHTER_MONIT_QUERY_STEP_DEFAULT}}
+
+    declare -g PROM_API_QSTR="start=${DATE_START}&end=${DATE_END}&step=${QUERY_STEP}"
+
+    echo "INFO: Metrics config time range from=${DATE_START} to=${DATE_END} step=${QUERY_STEP}"
+    echo "INFO: Metrics human  time range from=[$(date -d "@${DATE_START}")] to [$(date -d "@${DATE_END}")]"
+    echo "INFO: Config Env GAHTER_MONIT_START_DATE: ${GAHTER_MONIT_START_DATE}"
+    echo "INFO: Config Env GAHTER_MONIT_END_DATE: ${GAHTER_MONIT_END_DATE}"
+    echo "INFO: Config Env GAHTER_MONIT_QUERY_STEP: ${GAHTER_MONIT_QUERY_STEP}"
+    echo "INFO: Config Env GATHER_MONIT_CUSTOM_METRICS: ${GATHER_MONIT_CUSTOM_METRICS}"
+    echo "INFO: Config Env GATHER_MONIT_DISCOVERY_PREFIXES: ${GATHER_MONIT_DISCOVERY_PREFIXES}"
+    echo "INFO: Prometheus endpoint: https://${PROM_HOST}"
+    echo "INFO: Prometheus base query: ${PROM_API}/<uri>?query=<metric>&${PROM_API_QSTR}"
+}
+
+function cleanup {
+  rm "${CA_BUNDLE}"
+}
+
+function oc_get {
+  oc get \
+    --certificate-authority="${CA_BUNDLE}" \
+    --token="${SS_TOKEN}" \
+    "$@"
+}
+
+function prom_get_api {
+    local API_URI="${PROM_API}/${1}"; shift
+
+    oc_get \
+        --server="https://${PROM_HOST}" \
+        --raw="${API_URI}"
+}
+
+function prom_get_query_range {
+    local METRIC="${1}"; shift
+    local FILE_OK="${PROM_PATH}/metric-${METRIC}.json.gz";
+    local FILE_ERR="${PROM_PATH}/metric-${METRIC}.stderr";
+    local API_URI="query_range?query=${METRIC}&${PROM_API_QSTR}"
+
+    echo "INFO: Collecting metric /query_range?query=${METRIC}"
+    prom_get_api "${API_URI}" 2> "${FILE_ERR}" | gzip > "${FILE_OK}"
+}
+
+#
+# Gather specific metrics by name.
+# Env var: GATHER_MONIT_CUSTOM_METRICS
+#
+function get_custom_metrics {
 
     if [[ -z "${GATHER_MONIT_CUSTOM_METRICS}" ]]; then
         return
     fi
+    echo "INFO: Collecting custom metrics..."
 
-    echo "INFO: Metrics will be collected from [$(date -d "@${DATE_START}")] to [$(date -d "@${DATE_END}")]"
     for METRIC in ${GATHER_MONIT_CUSTOM_METRICS}; do
-        echo "INFO: Getting metric range: ${METRIC}"
-        prom_query_range "${METRIC}" "${METRIC}"
+        prom_get_query_range "${METRIC}"
     done
 }
 
-# Discovery metrics from prefixes defined on environment GATHER_MONIT_DISCOVERY_PREFIXES
-function get_discovery_metrics() {
+#
+# Discovery and gather metrics by prefixes.
+# Env var: GATHER_MONIT_DISCOVERY_PREFIXES
+#
+function get_discovery_metrics {
 
     if [[ -z "${GATHER_MONIT_DISCOVERY_PREFIXES}" ]]; then
         return
     fi
+    echo "INFO: Collecting metrics by prefixes..."
 
-    echo "INFO: Discovery all metrics' name and save on ${MONITORING_PATH}/prometheus-metrics.txt"
-    "${CURL_CMD[@]}" \
-        -H "Authorization: Bearer ${OCP_TOKEN}" \
-        -H "Accept-encoding: gzip" \
-        -g "${PROM_URL}/api/v1/label/__name__/values" \
-        | gunzip \
-        | jq -r '.data[]' > "${MONITORING_PATH}/prometheus-metrics.txt"
+    #echo "INFO: Discovery all metrics' name and save on ${MONITORING_PATH}/prometheus-metrics.txt"
+    prom_get_api "label/__name__/values" \
+        | python2 -c \
+            'import json,sys;v=[];[ v.append(d) for d in json.load(sys.stdin)["data"]];print("\n".join(v))' \
+                > "${MONITORING_PATH}/prometheus-metrics.txt"
 
-    echo "INFO: Starting discovery metrics by prefixes..."
     # TODO: fix it O(m*n) ;(
     while read METRIC; do
         for PREFIX in ${GATHER_MONIT_DISCOVERY_PREFIXES}; do
             if [[ "${METRIC}" =~ ^${PREFIX}.* ]]; then
-                echo "INFO: Getting metric range: ${METRIC}"
-                prom_query_range "${METRIC}" "${METRIC}" ;
+                prom_get_query_range "${METRIC}"
             fi
         done
     done < "${MONITORING_PATH}/prometheus-metrics.txt"
 }
 
-# List all Dashboards from default folder (id=1) on Grafana - where OCP store it's dashboards
-function gf_discovery_dashboards() {
-
-    echo "INFO: Discovery Default Grafana Dashboard folder: ${GF_PATH}/dashboards.json"
-    "${CURL_CMD[@]}" \
-        -H "Authorization: Bearer ${OCP_TOKEN}" \
-        "${GF_URL}/api/search?folderIds=1" > "${GF_PATH}/dashboards.json"
-}
-
-# Parse and download all Dashboards discovered from Default folder,
-# then collect it's metrics from Prometheus API.
-function gf_discovery_metrics_from_dashboards() {
-
-    install_jq
-    echo -ne "INFO: Extract discovered dashboards: ${GF_PATH}/dashboards.txt"
-    ${JQ_PATH} \
-        -r '.[] | .uri +":"+ .uid' ${GF_PATH}/dashboards.json \
-        | awk -F'db/' '{print$2}' \
-        | awk '{print$1":"$2}' > ${GF_PATH}/dashboards.txt
-    echo " [$(wc -l ${GF_PATH}/dashboards.txt |awk '{print$1}')]"
-
-    while read -r DASHBOARD; do
-        NAME=$(echo "${DASHBOARD}" |awk -F':' '{print$1}')
-        DUID=$(echo "${DASHBOARD}" |awk -F':' '{print$2}')
-
-        echo "INFO: Getting Dashboard ${NAME}"
-        "${CURL_CMD[@]}" \
-            -H "Authorization: Bearer ${OCP_TOKEN}" \
-            "${GF_URL}/api/dashboards/uid/${DUID}" > "${GF_PATH}/dashboard_${NAME}.json"
-
-        ${JQ_PATH} -r '.dashboard.rows[].panels[].targets[].expr |match("\\(([\\w:]+){.*").captures[].string' \
-            "${GF_PATH}/dashboard_${NAME}.json" > "${GF_PATH}/dashboard_${NAME}_metrics.txt"
-    done < "${GF_PATH}/dashboards.txt"
-
-    echo -ne "INFO: Grouping all dashboards' metrics to ${GF_PATH}/dashboards_metrics.txt"
-    sort -u ${GF_PATH}/dashboard_*_metrics.txt > "${GF_PATH}/dashboards_metrics.txt"
-    echo " [$(wc -l ${GF_PATH}/dashboards_metrics.txt |awk '{print$1}')]"
-
-    echo "INFO: Gathering discovered metrics' data points"
-    while read -r METRIC; do
-        echo "INFO: Getting metric range: ${METRIC}"
-        prom_query_range "${METRIC}" "${METRIC}"
-    done < "${GF_PATH}/dashboards_metrics.txt"
-}
-
-function get_grafana_metrics() {
-
-    ENABLE_DISCOVERY=${GATHER_MONIT_DISCOVERY_GRAFANA:-${GATHER_MONIT_DISCOVERY_GRAFANA_DEFAULT}}
-    if [[ "${ENABLE_DISCOVERY}" == "no" ]]; then
-        echo "INFO: Ignoring metrics from Grafana dashboards. GATHER_MONIT_DISCOVERY_GRAFANA=no"
-        return
-    fi
-
-    echo "INFO: Get metrics from Grafana dashboards"
-    gf_discovery_dashboards
-    gf_discovery_metrics_from_dashboards
-}
-
-
-function get_alerts() {
+#
+# Gather current alerts.
+#
+function get_alerts {
 
     set -o nounset
     set -o errexit
 
     # using oc get --raw because we directly control it and have standardized debugging on it
-    oc get \
-        --server="${PROM_URL}" \
-        --token="${SA_TOKEN}" \
-        --certificate-authority="${MONITORING_PATH}/ca-bundle.crt" \
-        --raw=/api/v1/rules?type=alert 2>"${MONITORING_PATH}/alert.stderr" > "${MONITORING_PATH}/alerts.json"
-
-    rm "${MONITORING_PATH}/ca-bundle.crt"
+    oc_get \
+        --server="https://${PROM_HOST}" \
+        --raw=/api/v1/rules?type=alert \
+            2> "${MONITORING_PATH}/alerts.err" \
+            >  "${MONITORING_PATH}/alerts.json"
 }
 
 #> Main
-# Get custom metrics custom
+init
+
+# Collect metrics by name
 get_custom_metrics
 
-# Get Grafana dashboards and it's metrics data points
-get_grafana_metrics
-
-# Get discovery metrics
+# Collect metrics by prefix
 get_discovery_metrics
 
-# Get Prometheus Alerts
+# Collect Prometheus Alerts
 get_alerts
 
 # force disk flush to ensure that all data gathered is accessible in the copy container
 echo "INFO: Must-gather monitoring finished"
+cleanup
 sync
